import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "../../Component/Header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
